import type { Metadata } from "next";
import ContentProvider from "../providers/ContentProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ContentProvider>{children}</ContentProvider>;
}
